spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/book_test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  poster: posters/

base:
  url: "http://localhost:8081"


server:
  port: 8081
